# Generated by Django 5.2.10 on 2026-06-09 07:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0031_company_from_email_company_smtp_host_and_more'),
        ('employees', '0019_customdepartment_description_customrole_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.BigIntegerField(blank=True, null=True)),
                ('project_code', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('client_email', models.CharField(blank=True, max_length=255, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('project_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('billing_type', models.CharField(blank=True, choices=[('Fixed Price', 'Fixed Price'), ('Hourly', 'Hourly'), ('Monthly Retainer', 'Monthly Retainer')], max_length=50, null=True)),
                ('payment_terms', models.CharField(blank=True, choices=[('Advance', 'Advance'), ('Milestone Based', 'Milestone Based'), ('Monthly', 'Monthly')], max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('project_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='Not Started', max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=50)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_projects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_role', models.CharField(max_length=100)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('hours_planned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('assignment_status', models.CharField(default='Active', max_length=50)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='employees.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_assignments',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company'], name='projects_company_408096_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_code'], name='projects_project_cceb9a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_manager'], name='projects_project_ce5ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_status'], name='projects_project_ea2c15_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['active_status'], name='projects_active__83624c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['planned_end_date'], name='projects_planned_aaed9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('company', 'project_code'), name='unique_company_project_code'),
        ),
        migrations.AddIndex(
            model_name='projectassignment',
            index=models.Index(fields=['company'], name='project_ass_company_a623b4_idx'),
        ),
        migrations.AddIndex(
            model_name='projectassignment',
            index=models.Index(fields=['project'], name='project_ass_project_914977_idx'),
        ),
        migrations.AddIndex(
            model_name='projectassignment',
            index=models.Index(fields=['employee'], name='project_ass_employe_eaa0f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectassignment',
            constraint=models.UniqueConstraint(fields=('project', 'employee'), name='unique_project_employee'),
        ),
    ]
