# Generated by Django 5.1 on 2026-06-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('Quarterly Price', 'Quarterly Price'), ('Fixed Price', 'Fixed Price'), ('Monthly Price', 'Monthly Price')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Milestone Based', 'Milestone Based')], max_length=50, null=True),
        ),
    ]
