# Generated by Django 5.1 on 2026-06-04 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0030_company_max_login_attempts_and_more'),
        ('employees', '0017_employee_employment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('departments', models.JSONField(default=list, help_text='List of department names/IDs participating in clearance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_templates', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='ResignationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separation_type', models.CharField(choices=[('RESIGNATION', 'Resignation'), ('TERMINATION', 'Termination'), ('RETIREMENT', 'Retirement'), ('CONTRACT_END', 'Contract End'), ('ABSCONDING', 'Absconding')], default='RESIGNATION', max_length=50)),
                ('reason', models.CharField(max_length=255)),
                ('detailed_explanation', models.TextField(blank=True)),
                ('submitted_on', models.DateTimeField(blank=True, null=True)),
                ('notice_period_days', models.PositiveIntegerField(default=0)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MANAGER_APPROVED', 'Manager Approved'), ('HR_APPROVED', 'HR Approved'), ('CLEARANCE_PENDING', 'Clearance Pending'), ('SETTLEMENT_PENDING', 'Settlement Pending'), ('READY_FOR_RELIEVING', 'Ready For Relieving'), ('RELIEVED', 'Relieved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50)),
                ('manager_remarks', models.TextField(blank=True)),
                ('hr_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignations', to='accounts.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignations', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='RelievingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RELIEVING_LETTER', 'Relieving Letter'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('NO_DUE', 'No Due Certificate'), ('SETTLEMENT', 'Full & Final Settlement')], max_length=50)),
                ('file_path', models.FileField(upload_to='separation/documents/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relieving_documents', to='accounts.company')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='separation.resignationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='FinalSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnings_payload', models.JSONField(default=dict)),
                ('deductions_payload', models.JSONField(default=dict)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resignation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_settlement', to='separation.resignationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_leaving', models.TextField()),
                ('work_environment_feedback', models.TextField(blank=True)),
                ('manager_feedback', models.TextField(blank=True)),
                ('company_feedback', models.TextField(blank=True)),
                ('rehire_eligible', models.BooleanField(default=True)),
                ('ratings', models.JSONField(default=dict, help_text='Store culture, team, compensation, growth, work_life ratings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resignation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interview', to='separation.resignationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_departments', to='employees.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_clearances', to='accounts.company')),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='separation.resignationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SeparationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('stage', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('HR', 'HR'), ('FINANCE', 'Finance')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='separation.resignationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SeparationChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separation_checklists', to='accounts.company')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeChecklistProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_progress', to='separation.resignationrequest')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='separation.separationchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='SeparationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('event_description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='separation.resignationrequest')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NoticePeriodPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255)),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_days', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_period_policies', to='accounts.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'is_active'], name='separation__company_5096bb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='resignationrequest',
            index=models.Index(fields=['company', 'status'], name='separation__company_f585cf_idx'),
        ),
        migrations.AddIndex(
            model_name='resignationrequest',
            index=models.Index(fields=['employee'], name='separation__employe_41236c_idx'),
        ),
    ]
