# Generated by Django 5.1 on 2026-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('separation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentclearance',
            name='cleared_by',
        ),
        migrations.RemoveField(
            model_name='departmentclearance',
            name='company',
        ),
        migrations.RemoveField(
            model_name='departmentclearance',
            name='resignation',
        ),
        migrations.RemoveField(
            model_name='employeechecklistprogress',
            name='checklist_item',
        ),
        migrations.RemoveField(
            model_name='employeechecklistprogress',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='employeechecklistprogress',
            name='resignation',
        ),
        migrations.RemoveField(
            model_name='exitinterview',
            name='resignation',
        ),
        migrations.RemoveField(
            model_name='noticeperiodpolicy',
            name='company',
        ),
        migrations.RemoveField(
            model_name='relievingdocument',
            name='company',
        ),
        migrations.RemoveField(
            model_name='relievingdocument',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='relievingdocument',
            name='resignation',
        ),
        migrations.RemoveField(
            model_name='separationapproval',
            name='action_by',
        ),
        migrations.RemoveField(
            model_name='separationapproval',
            name='resignation',
        ),
        migrations.RemoveField(
            model_name='separationchecklist',
            name='company',
        ),
        migrations.RemoveField(
            model_name='separationtimeline',
            name='resignation',
        ),
        migrations.RemoveField(
            model_name='resignationrequest',
            name='hr_remarks',
        ),
        migrations.RemoveField(
            model_name='resignationrequest',
            name='manager_remarks',
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='approval_history',
            field=models.JSONField(blank=True, default=list, help_text='Stores approval roles, actions, and remarks'),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='clearance_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores department-wise clearance status'),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='documents',
            field=models.JSONField(blank=True, default=dict, help_text='Stores paths to generated separation documents'),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='exit_interview',
            field=models.JSONField(blank=True, default=dict, help_text='Stores exit interview feedback and ratings'),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='timeline',
            field=models.JSONField(blank=True, default=list, help_text='Stores timestamped events for tracking'),
        ),
        migrations.AlterField(
            model_name='finalsettlement',
            name='deductions_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='finalsettlement',
            name='earnings_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='ClearanceTemplate',
        ),
        migrations.DeleteModel(
            name='DepartmentClearance',
        ),
        migrations.DeleteModel(
            name='EmployeeChecklistProgress',
        ),
        migrations.DeleteModel(
            name='ExitInterview',
        ),
        migrations.DeleteModel(
            name='NoticePeriodPolicy',
        ),
        migrations.DeleteModel(
            name='RelievingDocument',
        ),
        migrations.DeleteModel(
            name='SeparationApproval',
        ),
        migrations.DeleteModel(
            name='SeparationChecklist',
        ),
        migrations.DeleteModel(
            name='SeparationTimeline',
        ),
    ]
