# Generated by Django 5.1 on 2026-06-05 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetreturn_cleared_at_assetreturn_cleared_by_and_more'),
        ('separation', '0002_remove_departmentclearance_cleared_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalsettlement',
            name='deductions_payload',
        ),
        migrations.AddField(
            model_name='finalsettlement',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsettlement',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsettlement',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='finalsettlement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finalsettlement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('DISPUTED', 'Disputed')], default='DRAFT', max_length=50),
        ),
        migrations.CreateModel(
            name='FinalSettlementDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('ASSET_DAMAGE', 'Asset Damage'), ('ASSET_LOST', 'Asset Lost'), ('LOAN', 'Loan'), ('ADVANCE', 'Advance'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.assetreturn')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='separation.finalsettlement')),
            ],
        ),
    ]
