# Generated by Django 5.1 on 2026-06-10 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('separation', '0002_add_notice_shortfall_fields_to_finalsettlement'),
        ('separation', '0003_remove_finalsettlement_deductions_payload_and_more'),
    ]

    operations = [
    ]
