# Generated by Django 5.1 on 2026-03-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_assign_default_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.CharField(blank=True, choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium')], default='BASIC', max_length=20),
        ),
    ]
