# Generated by Django 5.1 on 2026-03-15 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_company_plan'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pricing_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='billing.pricingplan'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_period_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
