# Generated by Django 5.1 on 2026-03-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_fix_all_tables_autoincrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, help_text='Optional domain for tenant (e.g. acme.hrms.com)', max_length=255),
        ),
    ]
