# Generated by Django 5.1 on 2026-04-03 10:49

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_company_updated_at_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo for payslips and branding (PNG, JPEG, WebP).', null=True, upload_to=apps.accounts.models.company_logo_upload_to),
        ),
    ]
