# Generated by Django 5.2.10 on 2026-05-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='billing_action_stopped',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
