# Generated by Django 5.2.10 on 2026-05-21 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_company_billing_action_stopped'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AlterModelOptions(
            name='temporarypasswordrecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='company',
            name='pricing_plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_changed_at',
        ),
        migrations.AddField(
            model_name='user',
            name='billing_action_stopped',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='departments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_calendar',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(help_text='Unique code or short identifier for the company', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, help_text='Custom domain or subdomain for white-labeling', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='temporarypasswordrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_temp_passwords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temporarypasswordrecord',
            name='email_sent_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='temporarypasswordrecord',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='temporarypasswordrecord',
            name='purpose',
            field=models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('PASSWORD_RESET', 'Password Reset')], max_length=20),
        ),
        migrations.AlterField(
            model_name='temporarypasswordrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_password_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
