# Generated by Django 5.1 on 2026-05-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('HR', 'HR'), ('FINANCE_ADMIN', 'Finance Admin'), ('EMPLOYEE', 'Employee')], db_index=True, default='EMPLOYEE', max_length=20),
        ),
    ]
