# Generated by Django 5.1 on 2026-05-25 12:10

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=apps.accounts.models.default_enabled_modules),
        ),
    ]
