# Generated by Django 5.1 on 2026-05-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_company_address_company_gstin_company_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_account_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_ifsc',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
