# Generated by Django 5.1 on 2026-05-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_company_bank_account_no_company_bank_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
