# Generated by Django 5.2.10 on 2026-05-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hr_permissions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
