# Generated by Django 5.2.10 on 2026-05-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_user_hr_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='hr/documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='hr/documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='education_certificate',
            field=models.FileField(blank=True, null=True, upload_to='hr/documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, upload_to='hr/documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='hr/documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='hr/documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hr/photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='hr/documents/'),
        ),
    ]
