# Generated by Django 5.2.10 on 2026-05-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_user_aadhar_card_user_address_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hr_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
