# Generated by Django 5.1 on 2026-06-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='state_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
