# Generated by Django 5.1 on 2026-06-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_company_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_login_attempts',
            field=models.IntegerField(default=5, help_text='Account locks after this many failed logins. 0 to disable.'),
        ),
        migrations.AddField(
            model_name='company',
            name='min_password_length',
            field=models.IntegerField(default=8, help_text='Minimum characters required for passwords.'),
        ),
        migrations.AddField(
            model_name='company',
            name='password_expiry_days',
            field=models.IntegerField(default=90, help_text='Force password reset after this many days (0 = never).'),
        ),
        migrations.AddField(
            model_name='company',
            name='require_mfa',
            field=models.BooleanField(default=False, help_text='Enforce Multi-Factor Authentication for all users.'),
        ),
    ]
