# Generated by Django 5.1 on 2026-06-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_company_max_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='from_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Encrypted SMTP password', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='use_company_smtp',
            field=models.BooleanField(default=False, help_text='Use company-specific SMTP settings instead of global defaults.'),
        ),
    ]
