# Generated by Django 5.1 on 2026-06-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_company_from_email_company_smtp_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhar_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_proof',
        ),
        migrations.RemoveField(
            model_name='user',
            name='custom_roles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education_certificate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience_certificate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hr_details',
        ),
        migrations.RemoveField(
            model_name='user',
            name='offer_letter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_calendar',
        ),
    ]
