# Generated by Django 5.2.10 on 2026-02-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leavetype_leaverequest_leaveapprovallog_leavebalance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='encashable',
            field=models.BooleanField(default=False),
        ),
    ]
