# Generated by Django 5.2.10 on 2026-02-24 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_account_number_and_more'),
        ('leaves', '0003_leavetype_encashable'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
