# Generated by Django 5.2.10 on 2026-03-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_leaveaccruallog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
