# Generated by Django 5.2.10 on 2026-03-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_holiday'),
        ('leaves', '0008_leavetype_accrual_enhancements'),
    ]

    operations = [
    ]
