# Generated by Django 5.2.10 on 2026-05-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0010_add_company_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leavetype',
            name='unique_leave_type_per_company',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='company',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='company',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='company',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approval_trail',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
