# Generated by Django 5.1 on 2026-05-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0011_remove_leavetype_unique_leave_type_per_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.DeleteModel(
            name='LeaveAccrualLog',
        ),
    ]
