# Generated by Django 5.1 on 2026-06-02 08:33

import django.db.models.deletion
from django.db import migrations, models

def generate_leave_codes(apps, schema_editor):
    LeaveType = apps.get_model('leaves', 'LeaveType')
    for lt in LeaveType.objects.all():
        # simple logic: taking first letters of words in name
        code = "".join([word[0].upper() for word in lt.name.split() if word])
        if not code:
            code = "L"
            
        base_code = code
        counter = 1
        while LeaveType.objects.filter(company=lt.company, code=code).exclude(id=lt.id).exists():
            code = f"{base_code}{counter}"
            counter += 1
            
        lt.code = code
        lt.save(update_fields=['code'])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_user_hr_details'),
        ('leaves', '0012_delete_holiday_delete_leaveaccruallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='advance_notice_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allowed_during_probation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='applicable_departments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='applicable_designations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='applicable_employment_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='applicable_gender',
            field=models.CharField(choices=[('ALL', 'All'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='code',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='document_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='document_required_after_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='include_holidays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='include_weekends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_system_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_consecutive_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='prorate_for_new_joiners',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['company', 'code'], name='leaves_leav_company_4ae4d8_idx'),
        ),
        migrations.RunPython(generate_leave_codes, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_leave_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_leave_code_per_company'),
        ),
    ]
