# Generated by Django 5.1 on 2026-06-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0013_leavetype_advance_notice_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
    ]
