# Generated by Django 5.2.10 on 2026-06-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0014_leaverequest_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveApprovalLog',
        ),
    ]
