# Generated by Django 5.2.10 on 2026-05-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_razorpaywebhooklog_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pricing_plan',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='razorpay_plan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='razorpay_plan_yearly_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PricingPlan',
        ),
    ]
