# Generated by Django 5.2.10 on 2026-06-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_payment_company_remove_payment_pricing_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='payment_mode',
            field=models.CharField(default='online', help_text='online or cash', max_length=20),
        ),
    ]
