# Generated by Django 5.1 on 2026-05-23 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0019_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=255)),
                ('holiday_date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('PUBLIC', 'Public Holiday'), ('OPTIONAL', 'Optional Holiday'), ('COMPANY', 'Company Holiday'), ('FESTIVAL', 'Festival')], default='PUBLIC', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('ALL', 'All States'), ('AP', 'Andhra Pradesh'), ('TS', 'Telangana'), ('KA', 'Karnataka'), ('TN', 'Tamil Nadu'), ('MH', 'Maharashtra')], default='ALL', max_length=50)),
                ('country', models.CharField(default='India', max_length=50)),
                ('is_optional', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_holidays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['holiday_date'],
                'indexes': [models.Index(fields=['holiday_date'], name='holidays_ho_holiday_7a10bd_idx'), models.Index(fields=['company'], name='holidays_ho_company_894075_idx'), models.Index(fields=['state'], name='holidays_ho_state_392e79_idx')],
            },
        ),
    ]
