# Generated by Django 5.1 on 2026-05-23 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_company_logo'),
        ('holidays', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['from_date']},
        ),
        migrations.RemoveIndex(
            model_name='holiday',
            name='holidays_ho_holiday_7a10bd_idx',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='holiday_date',
            new_name='from_date',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='is_optional',
        ),
        migrations.AddField(
            model_name='holiday',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['from_date'], name='holidays_ho_from_da_f869f8_idx'),
        ),
    ]
