# Generated by Django 5.1 on 2026-05-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_alter_holiday_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='payment_type',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='PAID', max_length=20),
        ),
    ]
