# apps/attendance/constants.py

STATUS_PRESENT = "PRESENT"
STATUS_HALF_DAY = "HALF_DAY"
STATUS_ABSENT = "ABSENT"
STATUS_PAID_LEAVE = "PAID_LEAVE"
STATUS_UNPAID_LEAVE = "UNPAID_LEAVE"
STATUS_HOLIDAY = "HOLIDAY"
STATUS_WEEK_OFF = "WEEK_OFF"

ATTENDANCE_STATUS_CHOICES = [
    (STATUS_PRESENT, "Present"),
    (STATUS_HALF_DAY, "Half Day"),
    (STATUS_ABSENT, "Absent"),
    (STATUS_PAID_LEAVE, "Paid Leave"),
    (STATUS_UNPAID_LEAVE, "Unpaid Leave"),
    (STATUS_HOLIDAY, "Holiday"),
    (STATUS_WEEK_OFF, "Week Off"),
]