# Generated by Django 5.1 on 2026-03-08 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0010_customrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('MOBILE', 'Mobile'), ('MONITOR', 'Monitor'), ('OTHER', 'Other')], max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['asset_type'], name='assets_comp_asset_t_fb12f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('MOBILE', 'Mobile'), ('MONITOR', 'Monitor'), ('OTHER', 'Other')], max_length=50)),
                ('asset_name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('NOT_WORKING', 'Not Working')], max_length=20)),
                ('return_date', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_asset_returns', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_return_requests', to='employees.employee')),
            ],
            options={
                'ordering': ['-request_date'],
                'indexes': [models.Index(fields=['employee', 'status'], name='assets_asse_employe_3af7a0_idx'), models.Index(fields=['status'], name='assets_asse_status_0f8af5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('RETURNED', 'Returned')], db_index=True, default='ASSIGNED', max_length=20)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='employees.employee')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.companyasset')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'status'], name='assets_asse_employe_c83269_idx')],
            },
        ),
    ]
