# Generated by Django 5.1 on 2026-03-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetreturnrequest',
            name='asset_type',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('MOBILE', 'Mobile'), ('ID_CARD', 'ID Card'), ('MONITOR', 'Monitor'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companyasset',
            name='asset_type',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('MOBILE', 'Mobile'), ('ID_CARD', 'ID Card'), ('MONITOR', 'Monitor'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
