# Generated by Django 5.1 on 2026-03-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_company_tenant'),
        ('assets', '0002_alter_assetreturnrequest_asset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetassignment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='assetreturnrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_return_requests', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_assets', to='accounts.company'),
        ),
    ]
