# Generated by Django 5.1 on 2026-06-04 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='assetreturn',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
