# Generated by Django 5.2.10 on 2026-05-21 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_add_company_tenant'),
        ('employees', '0014_remove_employeehistory_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('MOBILE', 'Mobile'), ('ID_CARD', 'ID Card'), ('MONITOR', 'Monitor'), ('OTHER', 'Other')], max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('RETURNED', 'Returned'), ('PENDING', 'Pending')], db_index=True, default='PENDING', max_length=20)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='company',
        ),
        migrations.RemoveIndex(
            model_name='assetreturnrequest',
            name='assets_asse_employe_3af7a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='assetreturnrequest',
            name='assets_asse_status_0f8af5_idx',
        ),
        migrations.RemoveField(
            model_name='assetreturnrequest',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='assetreturnrequest',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='assetreturnrequest',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='assetreturnrequest',
            name='company',
        ),
        migrations.RemoveField(
            model_name='assetreturnrequest',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='assetreturnrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assetreturnrequest',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='assetreturnrequest',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='assetreturnrequest',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetreturnrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_return_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetreturnrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='assetreturnrequest',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='assets.asset'),
        ),
        migrations.DeleteModel(
            name='AssetAssignment',
        ),
        migrations.DeleteModel(
            name='CompanyAsset',
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='assets_asse_asset_t_529092_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['employee', 'status'], name='assets_asse_employe_843326_idx'),
        ),
    ]
