# Generated by Django 5.1 on 2026-05-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_mfaotprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('email', 'Email'), ('security', 'Security')], db_index=True, default='general', max_length=20),
        ),
    ]
