# Generated by Django 5.1 on 2026-05-25 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0004_add_transaction_bank_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit_amount__gt', 0), models.Q(('credit_amount', 0), ('credit_amount__isnull', True), _connector='OR')), models.Q(('credit_amount__gt', 0), models.Q(('debit_amount', 0), ('debit_amount__isnull', True), _connector='OR')), _connector='OR'), name='daybook_transaction_amount_check'),
        ),
    ]
