# Generated by Django 5.1 on 2026-05-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0005_transaction_deleted_at_transaction_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
