# Generated by Django 5.2.10 on 2026-02-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_marked_at_and_more'),
        ('employees', '0002_employee_address_proof_employee_education_cert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='manually_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_08d913_idx'),
        ),
    ]
