# Generated by Django 5.2.10 on 2026-02-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_holiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='manually_unlocked',
            new_name='locked',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='marked_at',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('PAID_LEAVE', 'Paid Leave'), ('UNPAID_LEAVE', 'Unpaid Leave'), ('HOLIDAY', 'Holiday'), ('WEEK_OFF', 'Week Off')], max_length=20),
        ),
    ]
