# Generated by Django 5.2.10 on 2026-02-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Policy', max_length=100)),
                ('weekend_days', models.JSONField(default=list)),
                ('second_saturday_off', models.BooleanField(default=False)),
                ('fourth_saturday_off', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
