# Generated by Django 5.2.10 on 2026-02-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_weekendpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_minutes', models.IntegerField(default=15)),
                ('is_night_shift', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weekend_days', models.JSONField(default=list)),
                ('second_saturday_off', models.BooleanField(default=False)),
                ('fourth_saturday_off', models.BooleanField(default=False)),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WeekendPolicy',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('OFFICE', 'Office'), ('WFH', 'Work From Home'), ('FIELD', 'Field Work')], default='OFFICE', max_length=20),
        ),
    ]
