# Generated by Django 5.2.10 on 2026-02-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_shift_workcalendar_delete_weekendpolicy_and_more'),
        ('employees', '0006_employee_is_work_from_home_employee_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('PAID_LEAVE', 'Paid Leave'), ('UNPAID_LEAVE', 'Unpaid Leave'), ('HOLIDAY', 'Holiday'), ('WEEK_OFF', 'Week Off')], default='PRESENT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance__status_132c06_idx'),
        ),
    ]
