# Generated by Django 5.2.10 on 2026-03-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('LEAVE_SYSTEM', 'Leave System'), ('AUTO_SYSTEM', 'Auto System')], default='MANUAL', max_length=20),
        ),
    ]
