# Generated by Django 5.2.10 on 2026-05-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_add_company_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='holiday',
            name='unique_attendance_holiday_per_company',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='company',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='company',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='company',
        ),
        migrations.RemoveField(
            model_name='workcalendar',
            name='company',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
