# Generated by Django 5.2.10 on 2026-05-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_remove_holiday_unique_attendance_holiday_per_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('PAID_LEAVE', 'Paid Leave'), ('UNPAID_LEAVE', 'Unpaid Leave'), ('HOLIDAY', 'Holiday'), ('WEEK_OFF', 'Week Off'), ('PRESENT_ON_HOLIDAY', 'Present on Holiday'), ('WFH', 'Work From Home'), ('MISSED_PUNCH', 'Missed Punch')], default='PRESENT', max_length=20),
        ),
    ]
