# Generated by Django 5.1 on 2026-05-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_attendance_status'),
        ('employees', '0015_remove_employee_shift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
