# Generated by Django 5.2.10 on 2026-02-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payslipemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipemaillog',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
