# Generated by Django 5.2.10 on 2026-02-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payslip_lop_days_payslip_lop_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='employee_pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employer_pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
