# Generated by Django 5.2.10 on 2026-02-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_payslip_employee_pf_payslip_employer_pf'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='pf_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pf_wage_ceiling_applicable',
            field=models.BooleanField(default=True),
        ),
    ]
