# Generated by Django 5.2.10 on 2026-02-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_payslip_pf_applicable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='esi_applicable',
            field=models.BooleanField(default=True),
        ),
    ]
