# Generated by Django 5.2.10 on 2026-02-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_salary_esi_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='employee_esi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employer_esi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
