# Generated by Django 5.2.10 on 2026-02-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_payslip_employee_esi_payslip_employer_esi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalTaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pt_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['min_salary'],
            },
        ),
        migrations.AddField(
            model_name='payslip',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
