# Generated by Django 5.2.10 on 2026-02-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_professionaltaxslab_payslip_professional_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='leave_encashment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='leave_encashment_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
