# Generated by Django 5.2.10 on 2026-02-24 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_account_number_and_more'),
        ('payroll', '0014_payslip_bank_account_number_payslip_bank_ifsc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='tax_regime',
            field=models.CharField(choices=[('OLD', 'Old'), ('NEW', 'New')], default='NEW', max_length=10),
        ),
        migrations.CreateModel(
            name='FullFinalSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_working_date', models.DateField()),
                ('salary_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leave_encashment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notice_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_final_settlements', to='employees.employee')),
            ],
        ),
    ]
