# Generated by Django 5.2.10 on 2026-02-28 09:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_is_work_from_home_employee_shift_and_more'),
        ('payroll', '0015_salary_tax_regime_fullfinalsettlement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollmonth',
            options={},
        ),
        migrations.AlterModelOptions(
            name='professionaltaxslab',
            options={},
        ),
        migrations.RemoveField(
            model_name='fullfinalsettlement',
            name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='payrollmonth',
            name='closed_on',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='absent_days',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='attendance_deduction',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='bank_ifsc',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='generated_on',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='half_days',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='late_days',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='late_penalty',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='leave_encashment_amount',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='leave_encashment_days',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='pf_applicable',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='pf_wage_ceiling_applicable',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='unpaid_leave_days',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='working_days',
        ),
        migrations.RemoveField(
            model_name='payslipemaillog',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='tax_regime',
        ),
        migrations.AddField(
            model_name='payrollmonth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='conveyance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='medical',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='conveyance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='fixed_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='medical',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='pf_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='pf_wage_ceiling_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fullfinalsettlement',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='fullfinalsettlement',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollmonth',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='basic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='fixed_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='lop_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslipemaillog',
            name='payslip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payslip'),
        ),
        migrations.AlterField(
            model_name='payslipemaillog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='professionaltaxslab',
            name='pt_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='basic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salary',
            name='esi_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
