# Generated by Django 5.2.10 on 2026-03-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_salaryrevision_employer_esi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='medical_insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
