# Generated by Django 5.2.10 on 2026-03-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_payslip_medical_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullfinalsettlement',
            name='status',
            field=models.CharField(choices=[('NOT PAID', 'Not Paid'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='NOT PAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('NOT PAID', 'Not Paid'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='NOT PAID', max_length=20),
        ),
    ]
