# Generated by Django 5.1 on 2026-03-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_alter_fullfinalsettlement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'Generated'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('NOT PAID', 'Not Paid')], default='GENERATED', max_length=20),
        ),
    ]
