# Generated by Django 5.1 on 2026-03-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_company_tenant'),
        ('payroll', '0023_salary_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollmonth',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fullfinalsettlement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_final_settlements', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='payrollmonth',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_months', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='professionaltaxslab',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_tax_slabs', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='salary',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='salaryrevision',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_revisions', to='accounts.company'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollmonth',
            unique_together={('company', 'year', 'month')},
        ),
    ]
