# Generated by Django 5.2.10 on 2026-05-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_add_company_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullfinalsettlement',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='payrollmonth',
            unique_together={('year', 'month')},
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='bank_reference',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='professionaltaxslab',
            name='company',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='company',
        ),
        migrations.RemoveField(
            model_name='salaryrevision',
            name='company',
        ),
        migrations.AddField(
            model_name='payslipemaillog',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslipemaillog',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payslipemaillog',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslipemaillog',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='revision_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('NOT PAID', 'Not Paid'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='NOT PAID', max_length=20),
        ),
        migrations.RemoveField(
            model_name='payrollmonth',
            name='company',
        ),
    ]
