# Generated by Django 5.1 on 2026-05-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_ensure_revision_history_column'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullFinalSettlement',
        ),
    ]
