# Generated by Django 5.2.10 on 2026-02-13 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('employment_type', models.CharField(default='Full-time', max_length=50)),
                ('joining_date', models.DateField()),
                ('work_location', models.CharField(blank=True, max_length=100)),
                ('reporting_manager', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('shift_type', models.CharField(blank=True, max_length=50)),
                ('working_hours', models.CharField(blank=True, max_length=50)),
                ('weekly_off', models.CharField(blank=True, max_length=50)),
                ('attendance_type', models.CharField(blank=True, max_length=50)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('ifsc', models.CharField(blank=True, max_length=20)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('pf_esi', models.BooleanField(default=False)),
                ('emergency_name', models.CharField(blank=True, max_length=100)),
                ('emergency_number', models.CharField(blank=True, max_length=15)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
