# Generated by Django 5.2.10 on 2026-02-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='employees/address_proofs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_cert',
            field=models.FileField(blank=True, null=True, upload_to='employees/education/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience_cert',
            field=models.FileField(blank=True, null=True, upload_to='employees/experience/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='employees/id_proofs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='employees/offers/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/profile_photos/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employees/resumes/'),
        ),
    ]
