# Generated by Django 5.2.10 on 2026-02-22 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_address_proof_employee_education_cert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address_proof',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='attendance_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='education_cert',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='experience_cert',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ifsc',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='offer_letter',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pan',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pf_esi',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shift_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='weekly_off',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='employees.employee')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
