# Generated by Django 5.2.10 on 2026-02-25 06:19

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='employees/address_proofs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_cert',
            field=models.FileField(blank=True, null=True, upload_to='employees/education_certificates/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='esi_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='esi_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience_cert',
            field=models.FileField(blank=True, null=True, upload_to='employees/experience_certificates/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='employees/id_proofs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifsc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='employees/offer_letters/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='pt_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='uan_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_index=True, help_text='Enter unique Employee ID (Example: EMP001, HR-2026-01)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Employee ID can contain letters, numbers and hyphens only.', regex='^[A-Za-z0-9\\-]+$')]),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='employees_e_departm_e28f46_idx'),
        ),
    ]
