# Generated by Django 5.2.10 on 2026-02-26 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_shift_workcalendar_delete_weekendpolicy_and_more'),
        ('employees', '0005_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_work_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shift'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workcalendar'),
        ),
    ]
