# Generated by Django 5.2.10 on 2026-03-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_is_work_from_home_employee_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='deductions',
        ),
    ]
