# Generated by Django 5.2.10 on 2026-03-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_allowances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pf_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
