# Generated by Django 5.2.10 on 2026-03-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_pf_number_alter_employee_uan_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id_proof',
        ),
        migrations.AddField(
            model_name='employee',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='employees/aadhar_cards/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='employees/pan_cards/'),
        ),
    ]
