# Generated by Django 5.1 on 2026-03-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_customdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
