# Generated by Django 5.1 on 2026-03-15 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_company_tenant'),
        ('attendance', '0013_add_company_tenant'),
        ('employees', '0012_employee_emergency_name_employee_emergency_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customdepartment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_departments', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='customdepartment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company'], name='employees_e_company_4fecd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='customdepartment',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_custom_department_per_company'),
        ),
        migrations.AddConstraint(
            model_name='customrole',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_custom_role_per_company'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'employee_id'), name='unique_employee_id_per_company'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'email'), name='unique_employee_email_per_company'),
        ),
    ]
