# Generated by Django 5.2.10 on 2026-05-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_add_company_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeehistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='employeehistory',
            name='employee',
        ),
        migrations.AlterModelOptions(
            name='customdepartment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customrole',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='customdepartment',
            name='unique_custom_department_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='customrole',
            name='unique_custom_role_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_employee_id_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_employee_email_per_company',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_company_4fecd2_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='notes',
        ),
        migrations.AddField(
            model_name='customdepartment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='EmployeeHistory',
        ),
    ]
