# Generated by Django 5.1 on 2026-05-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_remove_employeehistory_changed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='shift',
        ),
    ]
