# Generated by Django 5.2.10 on 2026-05-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_remove_employee_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
