# Generated by Django 5.1 on 2026-06-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_employee_emergency_name_employee_emergency_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ONBOARDING', 'Onboarding'), ('PROBATION', 'Probation'), ('NOTICE_PERIOD', 'Notice Period'), ('RELIEVED', 'Relieved'), ('TERMINATED', 'Terminated'), ('RETIRED', 'Retired')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
