# Generated by Django 5.1 on 2026-06-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_employee_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdepartment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customrole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
