# Generated by Django 5.1 on 2026-06-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_customdepartment_is_active_customrole_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdepartment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customrole',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
