# Generated by Django 5.1 on 2026-06-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_customdepartment_description_customrole_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='work_calendar',
        ),
    ]
